version: '3'

services:
  fake-smtp-server:
    image: gessnerfl/fake-smtp-server:2.2.1
    hostname: 'fake-smtp-server'
    restart: always
    environment:
      - FAKESMTP_AUTHENTICATION_USERNAME=myuser
      - FAKESMTP_AUTHENTICATION_PASSWORD=mysecretpassword
    ports:
      - 8025:8025 #expose smtp port
      - 8082:8080 #expose web ui
      - 8081:8081 #expose management api
