name: Application CI
on: [push, pull_request]
jobs:
    applications:
        name: oncokb test suite
        runs-on: ubuntu-latest
        timeout-minutes: 40
        env:
            NODE_VERSION: 12.16.1
            SPRING_OUTPUT_ANSI_ENABLED: DETECT
            SPRING_JPA_SHOW_SQL: false
            JHI_DISABLE_WEBPACK_LOGS: true
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.16.1
            - uses: actions/setup-java@v1
              with:
                  java-version: '11.x'
            - name: Stop MySQL server
              run: sudo /etc/init.d/mysql stop
            - name: Install node.js packages
              run: yarn install
#            - name: Run backend test
#              run: |
#                 chmod +x mvnw
#                 ./mvnw -ntp clean verify -P-webpack
#            - name: Run frontend test
#              run: yarn run test-ci
            - name: Package application
              run: ./mvnw -ntp package -Pprod -DskipTests
